### ISSUE TITLE
Asking for help with dataset

### ISSUE THREAD

**Issue by allmancy13** [muzishen/Pet-ReID-IMAG#1]
Hello!
I found your repository, and it means you are taking part in the contest and deal with the data.
I had unfortunately lost my copy of training data (pet_biometric_challenge_2022.zip) - and now the access expired. Could i please ask you to share your copy, please? I will really appreciate any help. I know I am late with the contest - but I am really interested in working on the data.
Please excuse me for asking, but I feel really desperate about that - and still found no way to contact the organizers directly.
Arianna

**Comment by muzishen** [comment]
> 你好！ 我找到了您的存储库，这意味着您正在参加比赛并处理数据。 不幸的是，我丢失了我的训练数据副本 (pet_biometric_challenge_2022.zip) - 现在访问权限已过期。 我可以请你分享你的副本吗？ 我将非常感谢任何帮助。 我知道我参加比赛迟到了——但我真的对处理数据很感兴趣。 请原谅我的提问，但我对此感到非常绝望-仍然找不到直接联系组织者的方法。 阿里安娜
I will share the data link in a few days

**Comment by allmancy13** [comment]
Thak you very much! I am really wayting for it. 
(Thank you once again.)
Arianna

**Comment by muzishen** [comment]
> Thak you very much! I am really wayting for it. (Thank you once again.) Arianna

https://pan.baidu.com/s/1yYNJFuyrJy8kn5TVA5_Okw      [d0kc]
