### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by piggi999** [muzishen/Pet-ReID-IMAG#3]
Can you tell me how to put the datasets path during the testing? Are the inference datasets pictures of dog nose?

**Comment by muzishen** [comment]
> Can you tell me how to put the datasets path during the testing? Are the inference datasets pictures of dog nose?

See  https://github.com/muzishen/Pet-ReID-IMAG/blob/58eb04ba2c75d534e31fa3799a2012a1e736af31/pet_id/dataset.py#L26
Yes.

**Comment by piggi999** [comment]
> > Can you tell me how to put the datasets path during the testing? Are the inference datasets pictures of dog nose?
> 
> See
> 
> https://github.com/muzishen/Pet-ReID-IMAG/blob/58eb04ba2c75d534e31fa3799a2012a1e736af31/pet_id/dataset.py#L26
> 
> 
> Yes.

Can you share the test dataset?

**Comment by muzishen** [comment]
> > > Can you tell me how to put the datasets path during the testing? Are the inference datasets pictures of dog nose?
> > 
> > 
> > See
> > https://github.com/muzishen/Pet-ReID-IMAG/blob/58eb04ba2c75d534e31fa3799a2012a1e736af31/pet_id/dataset.py#L26
> > 
> > Yes.
> 
> Can you share the test dataset?

Sorry, according to the agreement, you have to request the test dataset from the sponsor.
