### ISSUE TITLE
线上测试集都由难样本组成，和训练集不一致，请问有什么迭代模型的技巧吗？

### ISSUE THREAD

**Issue by SCZwangxiao** [muzishen/Pet-ReID-IMAG#4]
线上测试集都是比较难的样本，我在比赛的时候时常发现，自己划分的验证集结果提升和线上的不一致。例如我尝试难样本挖掘，在自己划分的（多个）验证集上就没有收益。

**Comment by muzishen** [comment]
不好意思，回复晚了。
 比赛指标用的是AUC，这个指标对如何划分数据集（依据随机划分数据的难易程度）很敏感。
采用5折交叉验证可能更加稳定些。
这个比赛我认为更多的是需要关注细粒度。
